import json
recommender_prompts = {
    "morning:intro:1": {"suid": 23,
        "vsid": '6747',
        "message": "It is time for your morning messages to highlight the positive aspects of your caregiving and provide some encouraging words to start the day!",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "morning:gen_message:1": {"suid": 0,
        "vsid": 'NA',
        "message": "Good Morning, [caregiver name]. If at any time you feel that you or [care recipient name] are unsafe or need help, please follow your emergency plan.\n\n",
        "retrieval_object": "NA",
        "qtype": "NA"
        },
    "morning:positive:reflection:1": {"suid":30,
        "vsid":'6917',
        "message":"What has been rewarding about your caregiving?",
        "retrieval_object": "R007Q01",
        "qtype": "textbox"
        },
    "morning:positive:reflection:2": {"suid":30,
        "vsid":'6917',
        "message":"What do you most look forward to/enjoy/value about taking care of your family member?",
        "retrieval_object": "R007Q01",
        "qtype": "textbox"
        },
    "morning:positive:reflection:3": {"suid":30,
        "vsid":'6917',
        "message":"What are some good memories of your family member that you can draw on to keep you going?",
        "retrieval_object": "R007Q01",
        "qtype": "textbox"
        },
    "morning:positive:reflection:4": {"suid":30,
        "vsid":'6917',
        "message":"What kind of meaning do you find in caregiving?",
        "retrieval_object": "R007Q01",
        "qtype": "textbox"
        },
    "morning:positive:general:1": {"suid":19,
        "vsid":'6683',
        "message":"[MM] You\'re providing a familiar/secure/routine/pleasant environment for [care recipient name].",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:general:2": {"suid":19,
        "vsid":'6683',
        "message":"[MM] You know [care recipient name] best and will be able to identify subtle differences in their well-being.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:general:3": {"suid":19,
        "vsid":'6683',
        "message":"[MM] You know [care recipient name] best and can create meaningful and engaging activities that are best suited for him/her personally.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:general:4": {"suid":19,
        "vsid":'6683',
        "message":"[MM] Look at your card to send your intention for today",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:general:5": {"suid":19,
        "vsid":'6683',
        "message":"[MM] Think about what\'s important to you today. Look at the card if it would help.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:general:6": {"suid":19,
        "vsid":'6683',
        "message":"[MM] Caring for [care recipient name] is allowing you to spend quality/important time with [care recipient name].",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:general:7": {"suid":19,
        "vsid":'6683',
        "message":"[MM] Your providing a familiar environment for your family member during a difficult time.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:general:8": {"suid": 30,
        "vsid": '6917',
        "message": "[MM] Take a moment now to reflect on the following question: [MRM]",
        "retrieval_object": "R007Q01",
        "qtype": "textbox"
        },
    "morning:positive:accomp:1": {"suid":19,
        "vsid":'6683',
        "message":"[MM] You have developed many useful and creative skills by caring for your family member.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:accomp:2": {"suid":19,
        "vsid":'6683',
        "message":"[MM] Caring for your family member can help improve their well-being.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:feeling:1": {"suid":19,
        "vsid":'6683',
        "message":"[MM] As their caregiver, you are providing an important companionship for your family member.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:feeling:2": {"suid":19,
        "vsid":'6683',
        "message":"[MM] Caregiving has allowed you to return the love and care you have received from [care recipient name] over the years.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:feeling:3": {"suid":19,
        "vsid":'6683',
        "message":"[MM] Your care has allowed [care recipient name]\'s to preserve a sense of self-identity.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:feeling:4": {"suid":19,
        "vsid":'6683',
        "message":"[MM] You\'re following through on the promises you made in your wedding vows.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:family:1": {"suid":19,
        "vsid":'6683',
        "message":"[MM] You are an excellent role-model for your children.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:family:2": {"suid":19,
        "vsid":'6683',
        "message":"[MM] Your children appreciate the care you provide for [care recipient name].",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:family:3": {"suid":19,
        "vsid":'6683',
        "message":"[MM] You are setting a fantastic example of how to love and care for family.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:growth:1": {"suid":19,
        "vsid":'6683',
        "message":"[MM] Even though this has been challenging, you have been so strong.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:growth:2": {"suid":19,
        "vsid":'6683',
        "message":"[MM] You have overcome so much through this, and you\'re still going!",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:growth:3": {"suid":19,
        "vsid":'6683',
        "message":"[MM] Through caregiving you have strengthened your patience and ability to care for others\' needs.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:positive:growth:4": {"suid":19,
        "vsid":'6683',
        "message":"[MM] You have strengthened your ability to juggle many things at once by caring for [care recipient name].",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "morning:encouragement:general:1": {"suid":20,
        "vsid":'6699',
        "message":"You did a great job keeping yourself calm yesterday. [B] []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:general:2": {"suid":20,
        "vsid":'6699',
        "message":"Self-care means learning how to give the best version of yourself to the people who depend on you. [B] []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:general:3": {"suid":20,
        "vsid":'6699',
        "message":"Stress tries to stop you from giving your best to your family members - and you are learning to reduce its influence on you. [B] []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:general:4": {"suid":20,
        "vsid":'6699',
        "message":"[B] Great job keeping your emotions under control yesterday. []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:general:5": {"suid":20,
        "vsid":'6699',
        "message":"Your effort is making a bigger difference than you think. [B] []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:general:6": {"suid":20,
        "vsid":'6699',
        "message":"Brief moments of self-care are increasing the quality of the care you give. [B] []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:general:7": {"suid":20,
        "vsid":'6699',
        "message":"It\'s hard to care for others when you haven\'t cared for yourself, and you did a good job caring for yourself yesterday. []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:general:8": {"suid":20,
        "vsid":'6699',
        "message":"[B] It takes extra effort to care for yourself, but this work is making a difference for you and your family member. []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:success:1": {"suid":20,
        "vsid":'6699',
        "message":"[A] made a big difference for you yesterday. [B] []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:success:2": {"suid":20,
        "vsid":'6699',
        "message":"[A] is hard work, but you\'re learning how to use it when you need it. []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:unsuccess:1": {"suid":20,
        "vsid":'6699',
        "message":"It takes a long time to master a new skill. [C] []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:unsuccess:2": {"suid":20,
        "vsid":'6699',
        "message":"Looks like it was difficult to implement [A]. [C] []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:unsuccessmult:1": {"suid":20,
        "vsid":'6699',
        "message":"It looks like it was a tough day. And, you were successful in doing [A]. [C] []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:unsuccessmult:2": {"suid":20,
        "vsid":'6699',
        "message":"Notice what\'s working, [A], and do that more. []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:encouragement:successmult:1": {"suid":20,
        "vsid":'6699',
        "message":"Yesterday seemed like it was really great. Here\'s one self-care tip that seemed particularly successful for you [A]. []1 Please send more encouraging words\n2 Please send more encouraging words later today\n3 Thanks!",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "morning:self_care_goal:1": {"suid":23,
        "vsid":'6747',
        "message":"Setting your Self-Care Goal:\n\nRemember that while you are providing care for a family member, you also need take care of yourself. Try to take some time now to set a self-care goal for today.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "morning:self_care_goal:2": {"suid":23,
        "vsid":'6747',
        "message":"Setting your Self-Care Goal:\n\nNow would be a good time to create a self-care goal for today.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "morning:self_care_goal:3": {"suid":23,
        "vsid":'6747',
        "message":"Setting your Self-Care Goal:\n\nTake a moment to set your daily intention to care for yourself in some way.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:check_in:reactive:1": {"suid": 20,
         "vsid": '6699',
         "message": "It seems like you and [care recipient name] may be experiencing a stressful situation. []1 Yes I am stressed, please send a recommendation at this time \n2 Yes I am stressed, but I do not want a recommendation at this time \n3 No I am not stressed and I do not want a recommendation at this time \n4 No I am not stressed, but I would like a recommendation at this time",
         "retrieval_object": "R002Q01",
         "qtype": "radio"
         },
    "daytime:check_in:reactive:2": {"suid": 23,
         "vsid": '6747',
         "message": "Take a moment to scan your current environment for distractions. For example, is the TV too loud? Is the room too warm or cold? Do you have a lot of visitors? Have you had a busy day?",
         "retrieval_object": "endtime",
         "qtype": "message received"
         },
    "daytime:check_in:proactive:1": {"suid": 19,
        "vsid": '6683',
        "message": "Now might be a good time to try a stress management tip.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:recomm:timeout:1": {"suid": 23,
        "vsid": '6747',
        "message": "Now might be a good time to take a brief break.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:timeout:2": {"suid": 23,
        "vsid": '6747',
        "message": "Take a quick moment for yourself.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:timeout:3": {"suid": 23,
        "vsid": '6747',
        "message": "Take some time to \"put on your oxygen mask.\"",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:timeout:4": {"suid": 23,
        "vsid": '6747',
        "message": "Step away for a moment.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:timeout:5": {"suid": 23,
        "vsid": '6747',
        "message": "It seems like this could be a good time to take a time-out.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:timeout:6": {"suid": 23,
        "vsid": '6747',
        "message": "Feel free to step away if you need to collect your thoughts.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:timeout:7": {"suid": 23,
        "vsid": '6747',
        "message": "Feel free to step away if you need to settle yourself.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:timeout:8": {"suid": 23,
        "vsid": '6747',
        "message": "It seems like you could use some uninterrupted personal time, can you engage your family member in an activity that they enjoy?",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:timeout:9": {"suid": 23,
        "vsid": '6747',
        "message": "Engage [care recipient name] in an engaging activity and give yourself a few moments of personal time?",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:breathing:1": {"suid": 23,
        "vsid": '6747',
        "message": "Try some breathing exercises on your mindfulness training app.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:breathing:2": {"suid": 23,
        "vsid": '6747',
        "message": "Now is a good time to perform a breathing meditation using the mindfulness app or one of these recordings. [AudioAddon: breathing]",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:breathing:3": {"suid": 23,
        "vsid": '6747',
        "message": "Now is a good time to perform a breathing exercise. Please use a guided breathing from either the mindfulness app or the list provided below. [AudioAddon: breathing]",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:bodyscan:1": {"suid": 23,
        "vsid": '6747',
        "message": "Open your mindfulness training app or listen to one of these recordings and perform a body scan meditation. [AudioAddon: bodyscan]",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:bodyscan:2": {"suid": 23,
        "vsid": '6747',
        "message": "Perform a body scan using your mindfulness training app or the guided body scan meditation provided. [AudioAddon: bodyscan]",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:enjoyable:1": {"suid": 23,
        "vsid": '6747',
        "message": "You know [care recipient name] best, what\'s an activity that he/she has always enjoyed?-included in caregiver training.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:enjoyable:2": {"suid": 23,
        "vsid": '6747',
        "message": "Are you able to set up an activity for your family member now?",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:enjoyable:3": {"suid": 23,
        "vsid": '6747',
        "message": "Now might be a good time to start an activity with/for your family member.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:enjoyable:4": {"suid": 23,
        "vsid": '6747',
        "message": "You and your family member may benefit from engaging in an activity that you both enjoy.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:enjoyable:5": {"suid": 23,
        "vsid": '6747',
        "message": "Now might be a good time to do something you and [care recipient name] love doing together.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:enjoyable:6": {"suid": 23,
        "vsid": '6747',
        "message": "Can you start an activity with/for [care recipient name] that would make you both feel calmer?",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:enjoyable:7": {"suid": 23,
        "vsid": '6747',
        "message": "Trying engaging [care recipient name] in an activity or task that provides them with a sense of ease.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:enjoyable:8": {"suid": 23,
        "vsid": '6747',
        "message": "Grab your activity box",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:recomm:enjoyable:9": {"suid": 23,
        "vsid": '6747',
        "message": "Now might be a good time to [Load Dynamic Activities]",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "daytime:postrecomm:implement:1": {"suid": 22,
        "vsid": '6731',
        "message": "Did you do the stress management tip we sent?",
        "retrieval_object": "R000Q01",
        "qtype": "yes no"
        },
    "daytime:postrecomm:helpfulyes:1": {"suid":29,
        "vsid":'6787',
        "message":"On a scale from 0-10 how helpful was the stress management tip? [Likert] not helpful; very helpful",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "daytime:postrecomm:helpfulno:1": {"suid": 26,
        "vsid": '6767',
        "message": "What prevented you from doing the stress management tip?[]1 I didn\'t have time\n2 I didn\'t think it would help\n3 I didn\'t see the message",
        "retrieval_object": "QM001",
        "qtype": "multiple choice"
        },
    "evening:intro:1": {"suid": 23,
        "vsid": '6747',
        "message": "We will now review your day. We will ask a few questions about how you are feeling, if you were able to complete your self-care goal, and whether today's stress management tips were helpful.",
        "retrieval_object": "endtime",
        "qtype": "message received"
        },
    "evening:likert:stress:1": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how stressful was your day today? [Likert] not stressful at all; very stressful",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "evening:likert:lonely:1": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how lonely did you feel today? [Likert] not lonely at all; very lonely",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "evening:likert:health:1": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how would you say your physical health is today? [Likert] poor; excellent",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "evening:likert:health:2": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how down or \"blue\" did you feel today? [Likert] not at all; very down or \"blue\"",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "evening:textbox:interactions:1": {"suid":30,
        "vsid":'6917',
        "message":"About how many unpleasant interactions did you have with your family member today? Please provide a number estimate.",
        "retrieval_object": "R007Q01",
        "qtype": "textbox"
        },
    "evening:textbox:interactions:2": {"suid":30,
        "vsid":'6917',
        "message":"About how many pleasant interactions did you have with your family member today? Please provide a number estimate.",
        "retrieval_object": "R007Q01",
        "qtype": "textbox"
        },
    "evening:daily:goal:1": {"suid": 22,
        "vsid": '6731',
        "message": "Did you meet your self-care goal for today?",
        "retrieval_object": "R000Q01",
        "qtype": "yes no"
        },
    "evening:daily:goalyes:1": {"suid": 19,
        "vsid": '6683',
        "message": "Great job!",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "evening:daily:goalno:1": {"suid": 26,
        "vsid": '6767',
        "message": "What made it difficult for you to complete your goal?[]1 I didn\'t have enough time\n2 I was too tired or stressed\n3 I was distracted by other tasks or activities\n4 I did not set a goal",
        "retrieval_object": "QM001",
        "qtype": "multiple choice"
        },
    "evening:stress:manag:1": {"suid": 22,
        "vsid": '6731',
        "message": "Did you do a stress management tip today?",
        "retrieval_object": "R000Q01",
        "qtype": "yes no"
        },
    "evening:stress:managyes:1": {"suid": 26,
        "vsid": '6767',
        "message": "Which stress management tip or tips did you do today?[]1 Deep breathing\n2 Time out\n3 Body Scan\n4 Enjoyable Activity",
        "retrieval_object": "QM001",
        "qtype": "multiple choice"
        },
    "evening:stress:managyes:2": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how helpful was the stress management tip? [Likert] not helpful; very helpful",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "evening:stress:managno:1": {"suid": 26,
        "vsid": '6767',
        "message": "What prevented you from doing the stress management tip(s)?[]1 I didn\'t have time.\n2 I didn\'t think it would help.\n3 I didn\'t see the message(s).",
        "retrieval_object": "QM001",
        "qtype": "multiple choice"
        },
    "evening:system:helpful:1": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how helpful were today\'s stress management tips? [Likert] not helpful; very helpful",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "evening:system:helpful:2": {"suid": 26,
        "vsid": '6767',
        "message": "Which stress management tip helped most?[]1 Body Scan\n2 Time out\n3 Enjoyable Activity\n4 Deep Breathing",
        "retrieval_object": "QM001",
        "qtype": "multiple choice"
        },
    "evening:system:helpful:3": {"suid": 26,
        "vsid": '6767',
        "message": "Did any of the stress management tips help reduce your stress?[]1 Body Scan\n2 Time Out\n3 Enjoyable Activity\n4 Deep Breathing",
        "retrieval_object": "QM001",
        "qtype": "multiple choice"
        },
    "evening:reminder:battery:1": {"suid": 19,
        "vsid": '6683',
        "message": "Goodnight! Please don't forget to charge your phone.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "weekly:survey:1": {"suid": 26,
        "vsid": '6767',
        "message": "This week, which tips have been the most helpful?[]1 Body Scan\n2 Deep Breathing\n3 Enjoyable activities\n4 Time Out\n5 Reflecting on the positive aspects of caregiving\n6 Receiving encouraging words in the morning\n7 Setting my morning self-care goal",
        "retrieval_object": "QM001",
        "qtype": "multiple choice"
        },
    "weekly:messages:1": {"suid": 22,
        "vsid": '6731',
        "message": "Do you like the number of messages you receive in a day?",
        "retrieval_object": "R000Q01",
        "qtype": "yes no"
        },
    "weekly:messages:no:1": {"suid": 20,
        "vsid": '6699',
        "message": "Would you like:[]1 More Messages\n2 Fewer Messages\n3 No Change",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "weekly:msgetime:1": {"suid": 22,
        "vsid": '6731',
        "message": "Do you still like the amount of time between messages?",
        "retrieval_object": "R000Q01",
        "qtype": "yes no"
        },
    "weekly:msgetime:no:1": {"suid": 20,
        "vsid": '6699',
        "message": "How would you like to change the amount of time?[]1 More time between messages\n2 Less time between messages\n3 No Change",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "weekly:startstop:1": {"suid": 22,
        "vsid": '6731',
        "message": "Do you still like the start and stop time for the messages?",
        "retrieval_object": "R000Q01",
        "qtype": "yes no"
        },
    "weekly:startstop:start:1": {"suid": 20,
        "vsid": '6699',
        "message": "Please choose your preferred start time:[]1 2 hours earlier\n2 1.5 hours earlier\n3 1 hour earlier\n4 30 minutes earlier\n5 No Change\n6 30 minutes later\n7 1 hour later\n8 1.5 hours later\n9 2 hours later",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "weekly:startstop:stop:1": {"suid": 20,
        "vsid": '6699',
        "message": "Please choose your preferred end time:[]1 2 hours earlier\n2 1.5 hours earlier\n3 1 hour earlier\n4 30 minutes earlier\n5 No Change\n6 30 minutes later\n7 1 hour later\n8 1.5 hours later\n9 2 hours later",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "recomm_images":{'timeout':['timeout_pic.png','width:300px'],
        'breathing':['breathing_pic.png','width:300px'],
        'bodyscan':['mindfulness_pic.png','width:300px'],
        'enjoyable':['meaningful_pic.png','width:300px']
        },
    "morning:addon:A":{'timeout':'Taking a time out',
        'breathing': 'Taking a few deep breaths',
        'bodyscan':'Performing a body scan',
        'enjoyable':'Engaging your family member in a enjoyable activity'
        },
    "morning:addon:B":['Well done!',
        'Keep up the good work!',
        'You are doing so well.',
        'You are doing a great job.',
        'Celebrate small victories!',
        'Nice work!',
        'You are doing great.'],
    "morning:addon:C":['Hang in there.',
        'Remember you are doing this for important reasons.',
        'Being a caregiver is hard work.',
        'Not every day will be perfect.',
        'Remember to give yourself a break, too.',
        'Show yourself some kindness and compassion.',
        'Be patient with yourself.',
        'Focus on your success.'],
    "recomm:checkin:distract":['Is the TV too loud?',
        'Is the room too warm/cold?',
        'Do you have a lot of visitors?',
        'Have you had a busy day?'],
    "[AudioAddon: breathing]":"Breathing Meditation Guided by Andria: In this guided meditation, Andria's soothing voice guides you through a breathing exercise. [Audio: andriaBreathing1.mp3] Breathing Meditation Guided by Pam: In this guided meditation, Pam uses her cheerful voice to guide you through a breathing exercise. [Audio: pamBreathingNoMusic1.mp3] Breathing Meditation with Music Guided by Pam: In this guided meditation with accompanying music, Pam uses her cheerful voice to guide you through a breathing exercise. [Audio: pamBreathingMusic1.mp3]",
    "[AudioAddon: bodyscan]":"Body Scan Meditation Guided by Andria: In this guided meditation, Andria will use a calm, crisp voice to guide you in bringing awareness to your body. [Audio: andriaBodyScan1.mp3] Body Scan Meditation Guided by Pam: In this guided meditation, Pam uses an upbeat style to guide you in bringing awareness to your body. [Audio: pamBodyScanNoMusic1.mp3] Body Scan Meditation with Music Guided by Pam: In this guided meditation, Pam uses an upbeat voice and soothing background music to guide you in bringing awareness to your body. [Audio: pamBodyScanMusic1.mp3]",
    "baseline:recomm:likertconfirm:1": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how stressed or tense do you feel right now? [Likert] not tense or stressed at all; very tense or stressed",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "baseline:evening:likertstress:1": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how stressful was your day today? [Likert] not stressful at all; very stressful",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "baseline:evening:likertlonely:1": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how lonely did you feel today? [Likert] not lonely at all; very lonely",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "baseline:evening:likerthealth:1": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how would you say your physical health is today? [Likert] poor; excellent",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "baseline:evening:likerthealth:2": {"suid": 29,
        "vsid": '6787',
        "message": "On a scale from 0-10, how down or \"blue\" did you feel today? [Likert] not at all; very down or \"blue\"",
        "retrieval_object": "R006Q01",
        "qtype": "slide bar"
        },
    "baseline:evening:textboxinteractions:1": {"suid":30,
        "vsid":'6917',
        "message":"About how many unpleasant interactions did you have with your family member today? Please provide a number estimate.",
        "retrieval_object": "R007Q01",
        "qtype": "textbox"
        },
    "baseline:evening:textboxinteractions:2": {"suid":30,
        "vsid":'6917',
        "message":"About how many pleasant interactions did you have with your family member today? Please provide a number estimate.",
        "retrieval_object": "R007Q01",
        "qtype": "textbox"
        },
    "missed:recomm:1": {"suid": 19,
        "vsid": '6683',
        "message": "You have missed a recommendation message at [TIME]. Check back again later for more recommendation messages!",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "missed:evening:1": {"suid": 19,
        "vsid": '6683',
        "message": "You have missed the evening messages. Check back again tomorrow for the morning messages!",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "missed:morning:1": {"suid": 19,
        "vsid": '6683',
        "message": "You have missed the morning messages. Check back again later for recommendation messages!",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "request:button:1": {"suid": 20,
        "vsid": '6699',
        "message": "If you are experiencing a stressful situation, please click on the button below! []1 Experiencing Stressful Situation",
        "retrieval_object": "R002Q01",
        "qtype": "radio"
        },
    "daytime:affirmation:1": {"suid":19,
        "vsid":'6683',
        "message":"Wherever you are with your self-care is okay, it can be hard to start new habits.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:2": {"suid":19,
        "vsid":'6683',
        "message":"Try to be gentle with yourself today, sometimes we have bad days and sometimes we have good days, both are okay.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:3": {"suid":19,
        "vsid":'6683',
        "message":"Whatever you may feel throughout the day is okay. Try to simply reflect on how you feel and accept it without judgement.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:4": {"suid":19,
        "vsid":'6683',
        "message":"Remember it is okay to feel the way you do, whether it is positive or negative.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:5": {"suid":19,
        "vsid":'6683',
        "message":"When you are having a difficult moment with your family member, try to remember, \'This too shall pass.\'",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:6": {"suid":19,
        "vsid":'6683',
        "message":"Feelings of anger or frustration do not mean anything about you as a caregiver. These feelings happen to all of us; they make us human.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:7": {"suid":19,
        "vsid":'6683',
        "message":"Try to remember \"you know what you know, you know what you don't know.\"",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:8": {"suid":19,
        "vsid":'6683',
        "message":"Take a step back from doubting yourself. Try to think of it as it is.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:9": {"suid":19,
        "vsid":'6683',
        "message":"We all get the urge to change things we dislike as soon as we notice them. Try to let go of this urge the next time you feel it.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:10": {"suid":19,
        "vsid":'6683',
        "message":"Be at peace with where you are today.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:11": {"suid":19,
       "vsid":'6683',
       "message":"You are right where you are supposed to be.",
       "retrieval_object": "R001Q01",
       "qtype": "thanks"
       },
    "daytime:affirmation:12": {"suid":19,
       "vsid":'6683',
       "message":"When caregiving gets too stressful, I can try to do something that makes me feel positive.",
       "retrieval_object": "R001Q01",
       "qtype": "thanks"
       },
    "daytime:affirmation:13": {"suid":19,
        "vsid":'6683',
        "message":"When caregiving gets too stressful, I can focus on the positive aspects of the situation.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:14": {"suid":19,
        "vsid":'6683',
        "message":"When caregiving gets too stressful, I can find something good in what is happening.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:15": {"suid":19,
        "vsid":'6683',
        "message":"When caregiving gets too stressful, I can make the best of the situation.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:16": {"suid":19,
        "vsid":'6683',
        "message":"When caregiving gets too stressful, I can try to do something meaningful.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:17": {"suid":19,
        "vsid":'6683',
        "message":"When caregiving gets too stressful, I can focus on the benefits and not just the difficulties.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:18": {"suid":19,
        "vsid":'6683',
        "message":"When caregiving gets too stressful, I can learn from the experience.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:19": {"suid":19,
        "vsid":'6683',
        "message":"I am doing my best and I am proud of myself.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:20": {"suid":19,
        "vsid":'6683',
        "message":"I will give myself the care and attention I need to thrive.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:21": {"suid":19,
        "vsid":'6683',
        "message":"I will stay positive and work on one problem at a time.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:22": {"suid":19,
        "vsid":'6683',
        "message":"I am [care recipient name]\'s best caregiver, but I am not \"just\" a caregiver.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:23": {"suid":19,
        "vsid":'6683',
        "message":"I will find joy in the everyday day moments of life.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:24": {"suid":19,
        "vsid":'6683',
        "message":"I will not compare myself or my life with people on the internet or social media.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:25": {"suid":19,
        "vsid":'6683',
        "message":"I believe in myself and my abilities.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:26": {"suid":19,
        "vsid":'6683',
        "message":"I can do anything but not everything.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:27": {"suid":19,
        "vsid":'6683',
        "message":"I will do something for me today.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:28": {"suid":19,
        "vsid":'6683',
        "message":"I will focus on things that I can control.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:29": {"suid":19,
        "vsid":'6683',
        "message":"I am in control of my thoughts, feelings, and choices.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:30": {"suid":19,
        "vsid":'6683',
        "message":"I am not alone in my struggles.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:31": {"suid":19,
        "vsid":'6683',
        "message":"This situation is tough but so am I.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:32": {"suid":19,
        "vsid":'6683',
        "message":"The simple act of caring is heroic.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:33": {"suid":19,
        "vsid":'6683',
        "message":"I can do small things with great love.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:34": {"suid":19,
        "vsid":'6683',
        "message":"I am not sure how, but I know that I will.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:35": {"suid":19,
        "vsid":'6683',
        "message":"I am stronger because of my struggles.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:36": {"suid":19,
        "vsid":'6683',
        "message":"I don\'t have to be perfect to be amazing.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:37": {"suid":19,
        "vsid":'6683',
        "message":"I am courageous and graceful.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:38": {"suid":19,
        "vsid":'6683',
        "message":"I am at peace with my situation.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:39": {"suid":19,
        "vsid":'6683',
        "message":"I accept that I can only do so much.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:40": {"suid":19,
        "vsid":'6683',
        "message":"I am supporting my own well-being.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:41": {"suid":19,
        "vsid":'6683',
        "message":"I can support myself and my family member.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:42": {"suid":19,
        "vsid":'6683',
        "message":"I choose to care for myself just like I choose to care for my family member.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:43": {"suid":19,
        "vsid":'6683',
        "message":"The care I provide for my family member is honorable.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:44": {"suid":19,
        "vsid":'6683',
        "message":"The care I provide for my family member is respectable.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:45": {"suid":19,
        "vsid":'6683',
        "message":"I may not be able to change the situation, but I can make the best of it.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:46": {"suid":19,
        "vsid":'6683',
        "message":"Today was a rollercoaster, and that is okay.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:47": {"suid":19,
        "vsid":'6683',
        "message":"I am strong enough to endure.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:48": {"suid":19,
        "vsid":'6683',
        "message":"My emotions are valid.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:49": {"suid":19,
        "vsid":'6683',
        "message":"It is okay to feel my emotions.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:50": {"suid":19,
        "vsid":'6683',
        "message":"If I am frustrated, I know that is normal and natural.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:51": {"suid":19,
        "vsid":'6683',
        "message":"I am not alone in my struggle.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:52": {"suid":19,
        "vsid":'6683',
        "message":"It is okay to laugh.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:53": {"suid":19,
        "vsid":'6683',
        "message":"I can still be joyful about the good things.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:54": {"suid":19,
        "vsid":'6683',
        "message":"I can still find the humor in things.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:55": {"suid":19,
        "vsid":'6683',
        "message":"I celebrate my efforts.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:56": {"suid":19,
        "vsid":'6683',
        "message":"Caregiving is my superpower.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:57": {"suid":19,
        "vsid":'6683',
        "message":"I will take some time to get fresh air today.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:58": {"suid":19,
        "vsid":'6683',
        "message":"Taking moments for myself is also good for my family member.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:59": {"suid":19,
        "vsid":'6683',
        "message":"I grant myself forgiveness.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:60": {"suid":19,
        "vsid":'6683',
        "message":"I may lose my patience sometimes and that\'s okay.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:61": {"suid":19,
        "vsid":'6683',
        "message":"I am a role model to others.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:62": {"suid":19,
        "vsid":'6683',
        "message":"My efforts help humanity.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:63": {"suid":19,
        "vsid":'6683',
        "message":"I will have ups and downs, but this doesn\'t change who I am.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:64": {"suid":19,
        "vsid":'6683',
        "message":"One bad day does not reflect who I am as a person.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:65": {"suid":19,
        "vsid":'6683',
        "message":"I am allowed to feel angry.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:66": {"suid":19,
        "vsid":'6683',
        "message":"I am allowed to feel sad.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:67": {"suid":19,
        "vsid":'6683',
        "message":"I am allowed to feel happy.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:68": {"suid":19,
        "vsid":'6683',
        "message":"It is okay for me to set boundaries.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:69": {"suid":19,
        "vsid":'6683',
        "message":"Today, I will count all the amazing things I do.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:70": {"suid":19,
        "vsid":'6683',
        "message":"I don\'t have a solution for everything and that\'s okay.",
        "retrieval_object": "R001Q01",
        "qtype": "thanks"
        },
    "daytime:affirmation:71": {"suid":19,
       "vsid":'6683',
       "message":"I accept the things I cannot change.",
       "retrieval_object": "R001Q01",
       "qtype": "thanks"
       },
    "daytime:affirmation:72": {"suid":19,
       "vsid":'6683',
       "message":"I will celebrate a win today.",
       "retrieval_object": "R001Q01",
       "qtype": "thanks"
       }
}

jsonfile = open("json_prompts.json", 'w',encoding='utf-8')
json.dump(recommender_prompts, jsonfile)


# with open("json_prompts.json", 'r') as file:
#     json_prompts = json.load(file)
# message = 'morning_message1'
# print(json_prompts[message]['message'])
# _, _, message, _, _ = json_prompts[message].values()
# print(message)

# suid, vsid, message= recommender_prompts[4].values()
# print(suid, vsid, message)